name: Backend CI

'on':
  push:
    branches: [main]
  workflow_dispatch: {}

concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Run Tests
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout Code (clean)
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0

      - name: Setup Node.js (cache npm)
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          # Use a resilient glob so caching works even if only one lockfile exists
          cache-dependency-path: |
            **/package-lock.json

      - name: List lockfiles (debug)
        run: |
          echo "package-lock.json files:"
          git ls-files '**/package-lock.json' || true
          find . -maxdepth 3 -name package-lock.json

      - name: Show disk usage before
        run: df -h

      - name: Stop pm2 (if you REALLY need this)
        run: pm2 stop all || true

      # ----- Backend -----
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci

      - name: Run Backend Tests
        working-directory: ./backend
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        run: npm test

      - name: Create backend .env (no logging secrets)
        working-directory: ./backend
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        run: |
          {
            echo "MONGO_URI=$MONGO_URI"
            echo "JWT_SECRET=$JWT_SECRET"
            echo "PORT=$PORT"
          } > .env

      # ----- Frontend -----
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      # Optional: pm2 control (usually belongs in CD, not CI)
      - name: Start/Restart pm2 (optional)
        run: |
          pm2 start all || true
          pm2 restart all || true

      # Keep the self-hosted box clean (don’t nuke npm cache, that’s what we’re caching!)
      - name: Cleanup heavy artifacts
        if: always()
        run: |
          rm -rf backend/node_modules frontend/node_modules frontend/build || true
          pm2 flush || true

      - name: Show disk usage after
        if: always()
        run: df -h
